SELECT 'CREATE USER ${DB_USER} WITH ENCRYPTED PASSWORD ''${DB_PASS}'';'
WHERE NOT EXISTS (SELECT * FROM pg_user where usename = '${DB_USER}')\gexec

SELECT 'CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_MASTER_USER} ENCODING = "UTF8" CONNECTION LIMIT = -1;'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec

GRANT CONNECT, TEMP on database ${DB_NAME} to ${DB_USER};
